# Configuration file for CommandCost.
# The '§' character can be used for colour codes in this file.
# Message to be displayed when the money has been deducted from the players account.
command-success-message: '§e%amount% has been deducted from your account!'
# Message to be displayed when the user doesn't have enough money.
command-fail-message: '§cYou do not have enough money to execute this command!'
# Command names should be without the '/' character.
#
# Example:
#  mycommand:
#    cost: 60
# Please note that indentations need to be spaces, not tabs! If you are having problems getting your config file to work correctly, try putting it through a YAML parser.
# An online YAML parser can be found here:
# http://yaml-online-parser.appspot.com/
commands: