name: 'CommandCost'
main: com.bringholm.commandcost.Main
author: 'AlvinB'
version: '1.0'
softdepend: [Vault]
commands:
  cmdcost:
    description: cmdcost reload - Reloads the plugins configuration file.
    usage: /cmdcost reload
permissions:
  commandcost.*:
    children:
      commandcost.reload: true
      commandcost.bypass: true
  commandcost.reload:
    description: Allows you to use /cmdcost reload.
    default: op
  commandcost.bypass:
    description: Allows you to bypass the command cost.
    default: op
